baseurl: ''
url: 'https://turbodieseldecolombiagd.com'
name: 'Turbo Diesel de Colombia GD'
title: 'Turbo Diesel de Colombia GD'
author: Cristobal - T.D.D.G.
facebook: https://www.facebook.com/profile.php?id=100064895403683
maps: "https://maps.app.goo.gl/aDvF3ppBjMRaGK2y5"
telefono: "6013970149"
whatsapp: 3506329106
direccion:  "Carrera 82a #8C - 45, Bogotá"
email: ventas@turbodieseldecolombia.com.co

markdown: kramdown

permalink: :slug

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

collections:
  servicios:
    output: true
    permalink: /servicios/:path
  posts:
    output: true
    permalink: /blog/:slug


# Asegúrate de que tienes esta línea para habilitar los plugins en GitHub Pages
plugins:
  - jekyll-redirect-from

# Configuración opcional para personalizar el comportamiento del plugin
redirect_from:
  # Habilita la generación de redirecciones alternativas (no es necesario en la mayoría de los casos)
  # enabled: true

  # Ignora las redirecciones especificadas (útil si tienes conflictos)
  # ignore:
  #   - /ignorar-esta-redireccion

whitelist:
  - jekyll-redirect-from