baseurl: ''
url: 'https://turbodieseldecolombiagd.com'
name: 'Turbo Diesel de Colombia GD'
author: Henando - T.D.D.G.
instagram: https://www.instagram.com/holographic.ec/
facebook: https://web.facebook.com/profile.php?id=61560661795850
linkedin: https://www.linkedin.com/company/holographic-col/?viewAsMember=true
tiktok: https://www.tiktok.com/@holographicecuador
maps: "https://maps.app.goo.gl/JbC8V7Wjxtbo4MPYAs"
telefono: "6013970149"
direccion:  "Carrera 82a #8C - 45, Bogotá"

markdown: kramdown

permalink: :slug

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

collections:
  servicios:
    output: true
    permalink: /servicios/:path
  posts:
    output: true
    permalink: /blog/:slug
